name: uberjar
on: [push]

jobs:

  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - name: Download prebuilt uberjar
      run: curl -o metabase.jar -L https://heuristic-jepsen-a5dc85.netlify.app/metabase-5658fc06.jar
    - uses: actions/upload-artifact@v2
      with:
        name: uberjar
        path: './metabase.jar'

  check:
    runs-on: ubuntu-20.04
    needs: build
    timeout-minutes: 10
    strategy:
      matrix:
        java-version: [8, 11, 13]
    steps:
    - name: Prepare JRE (Java Run-time Environment)
      uses: actions/setup-java@v1
      with:
        java-package: jre
        java-version: ${{ matrix.java-version }}
    - run: java -version

    - uses: actions/download-artifact@v2
      name: Retrieve uberjar artifact
      with:
        name: uberjar

    - name: Launch uberjar
      run: |
        java -jar metabase.jar &
        sleep 180
      timeout-minutes: 5

    - name: Check API health
      if: always()
      run: curl -s localhost:3000/api/health

  known-java15-issue:
    continue-on-error: true
    runs-on: ubuntu-20.04
    needs: build
    timeout-minutes: 10
    steps:
    - name: Prepare JRE (Java Run-time Environment)
      uses: actions/setup-java@v1
      with:
        java-package: jre
        java-version: 15
    - run: java -version

    - uses: actions/download-artifact@v2
      name: Retrieve uberjar artifact
      with:
        name: uberjar

    - name: Launch uberjar
      run: |
        java -jar metabase.jar &
        sleep 180
      timeout-minutes: 5

    - name: Check API health
      if: always()
      run: curl -s localhost:3000/api/health
